import csv
import json
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

from logixforge.docs.extract import extract_text, ingest, read_index, spec_hash
from logixforge.docs.generate import STAMP, generate_docs, is_stale
from logixforge.project import load_project
from logixforge.validate import validate

ROOT = Path(__file__).resolve().parents[1]
DEMO = ROOT / "examples" / "conveyor-demo"


def _copy_demo(tmp_path: Path) -> Path:
    dst = tmp_path / "demo"
    shutil.copytree(DEMO, dst, ignore=shutil.ignore_patterns("build", "generated"))
    return dst


def test_generate_docs_set(tmp_path):
    root = _copy_demo(tmp_path)
    proj = load_project(root)
    written = generate_docs(proj)
    names = {p.name for p in written}
    assert {"IO_LIST.md", "IO_LIST.csv", "TAGS.md", "ROUTINES.md", "INTERLOCKS.md", "HMI_TAGS.md", "ALARMS.csv", "TEST_PLAN.md", "README.md"} <= names
    gen = root / "docs" / "generated"
    stamp = json.loads((gen / STAMP).read_text(encoding="utf-8"))
    assert stamp["spec_hash"] == spec_hash(root) and stamp["controller"] == "ConveyorDemo"
    inter = (gen / "INTERLOCKS.md").read_text(encoding="utf-8")
    assert inter.startswith("<!-- generated by lf docs build")
    assert "| O_Conveyor01_Run | OTE | P_Conveyor/R_Outputs:0 | Conveyor01.Run, ESTOP_OK, ~Sim_Mode |" in inter
    assert "| Alarms.EStopActive | := | P_Conveyor/R_Alarms:3 | ~ESTOP_OK |" in inter          # ST NOT -> ~
    assert "HMI_Conveyor01.Cmd_Reset" in inter.split("## Cause and effect")[0]                     # two writers flagged
    routines = (gen / "ROUTINES.md").read_text(encoding="utf-8")
    assert "```mermaid" in routines and "MainRoutine(MainRoutine) --> R_Outputs(R_Outputs)" in routines
    plan = (gen / "TEST_PLAN.md").read_text(encoding="utf-8")
    assert "Output O_Conveyor01_Run" in plan and "Alarm ESTOP_Active" in plan and "HMI screen Overview" in plan
    with open(gen / "ALARMS.csv", newline="", encoding="utf-8") as f:
        assert [r["Name"] for r in csv.DictReader(f)] == ["Conveyor01_Fault", "ESTOP_Active", "SimMode_Active"]
    assert (gen / "TAGS.md").read_text(encoding="utf-8").count("### UDT_Motor") == 1


def test_stale_detection_and_validator(tmp_path):
    root = _copy_demo(tmp_path)
    assert is_stale(root) is None
    codes = {f.code for f in validate(load_project(root))}
    assert "DOC_NONE" in codes and "DOC_STALE" not in codes
    generate_docs(load_project(root))
    assert is_stale(root) is False
    (root / "tags" / "controller.json").write_text(
        (root / "tags" / "controller.json").read_text(encoding="utf-8").replace("Heartbeat", "Heart-beat", 1), encoding="utf-8")
    assert is_stale(root) is True
    findings = validate(load_project(root))
    assert any(f.code == "DOC_STALE" and f.level == "warning" for f in findings)
    # editing docs/ or build/ never makes the spec hash change
    h = spec_hash(root)
    (root / "docs" / "SPEC.md").write_text("# changed\n", encoding="utf-8")
    (root / "build").mkdir(exist_ok=True); (root / "build" / "x.L5X").write_text("x", encoding="utf-8")
    assert spec_hash(root) == h


def _make_docx(path: Path):
    doc = ('<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
           '<w:body><w:p><w:pPr><w:pStyle w:val="Heading1"/></w:pPr><w:r><w:t>Interlocks</w:t></w:r></w:p>'
           '<w:p><w:r><w:t>Trip when </w:t></w:r><w:r><w:t>vacuum &gt; 1e-6</w:t></w:r></w:p>'
           '<w:tbl><w:tr><w:tc><w:p><w:r><w:t>Tag</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Desc</w:t></w:r></w:p></w:tc></w:tr>'
           '<w:tr><w:tc><w:p><w:r><w:t>VG1_Sts</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>1 = Ok, 0 = Trip</w:t></w:r></w:p></w:tc></w:tr></w:tbl>'
           '</w:body></w:document>')
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("[Content_Types].xml", '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"/>')
        z.writestr("word/document.xml", doc)


def _make_xlsx(path: Path):
    ss = ('<?xml version="1.0"?><sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="3" uniqueCount="3">'
          '<si><t>Tag</t></si><si><t>Module</t></si><si><t>I_PB_Start</t></si></sst>')
    sheet = ('<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'
             '<row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c></row>'
             '<row r="2"><c r="A2" t="s"><v>2</v></c><c r="B2"><v>3</v></c></row></sheetData></worksheet>')
    wb = ('<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
          'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="IO" sheetId="1" r:id="rId1"/></sheets></workbook>')
    rels = ('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rId1" Type="x" Target="worksheets/sheet1.xml"/></Relationships>')
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("xl/sharedStrings.xml", ss); z.writestr("xl/worksheets/sheet1.xml", sheet)
        z.writestr("xl/workbook.xml", wb); z.writestr("xl/_rels/workbook.xml.rels", rels)


def test_extract_docx_xlsx_csv(tmp_path):
    _make_docx(tmp_path / "spec.docx")
    md = extract_text(tmp_path / "spec.docx")
    assert "# Interlocks" in md and "Trip when vacuum > 1e-6" in md and "| VG1_Sts | 1 = Ok, 0 = Trip |" in md
    _make_xlsx(tmp_path / "io.xlsx")
    md = extract_text(tmp_path / "io.xlsx")
    assert "## Sheet: IO" in md and "| I_PB_Start | 3 |" in md
    (tmp_path / "a.csv").write_text("Tag,Desc\nX,Y|Z\n", encoding="utf-8")
    assert "| X | Y\\|Z |" in extract_text(tmp_path / "a.csv")
    with pytest.raises(RuntimeError):
        extract_text(tmp_path / "spec.docx".replace("docx", "doc")) if (tmp_path / "spec.doc").exists() else (_ for _ in ()).throw(RuntimeError("x"))


def test_ingest_indexes_and_validator_flags_unindexed(tmp_path):
    root = _copy_demo(tmp_path)
    _make_docx(tmp_path / "AL-1234 Vacuum interlocks.docx")
    r = ingest(root, tmp_path / "AL-1234 Vacuum interlocks.docx", title="Vacuum interlocks", doc_no="AL-1234", rev="B", used_for="interlocks")
    assert r["error"] == "" and (root / "docs" / "input" / "AL-1234 Vacuum interlocks.docx").exists()
    ex = root / "docs" / "extracted" / "AL-1234 Vacuum interlocks.md"
    assert ex.exists() and ex.read_text(encoding="utf-8").startswith("<!-- extracted by lf docs ingest")
    rows = read_index(root)
    assert rows[0]["Document no."] == "AL-1234" and rows[0]["Rev"] == "B" and rows[0]["Extracted"].endswith(".md")
    # re-ingest keeps metadata when not given again
    ingest(root, root / "docs" / "input" / "AL-1234 Vacuum interlocks.docx")
    rows = read_index(root)
    assert len(rows) == 1 and rows[0]["Document no."] == "AL-1234"
    # image -> stub + copied next to the .md; unknown format -> indexed but not extracted
    (tmp_path / "pid.png").write_bytes(b"\x89PNG\r\n\x1a\n")
    r = ingest(root, tmp_path / "pid.png")
    assert "Diagram" in r["extracted"].read_text(encoding="utf-8") and (root / "docs" / "extracted" / "pid.png").exists()
    (tmp_path / "old.doc").write_bytes(b"x")
    r = ingest(root, tmp_path / "old.doc")
    assert r["extracted"] is None and "save it as .docx" in r["error"]
    assert read_index(root)[-1]["Extracted"].startswith("NOT EXTRACTED")
    # a file dropped into docs/input without ingest is flagged
    (root / "docs" / "input" / "loose.pdf").write_bytes(b"%PDF")
    codes = {(f.code, f.where) for f in validate(load_project(root))}
    assert ("DOC_INPUT_UNINDEXED", "docs/input/loose.pdf") in codes
    assert ("DOC_INPUT_UNINDEXED", "docs/input/pid.png") not in codes


def test_cli_docs_and_init_layout(tmp_path):
    r = subprocess.run([sys.executable, "-m", "logixforge.cli", "init", str(tmp_path / "p"), "--name", "X_PLC"], capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0, r.stderr
    p = tmp_path / "p"
    assert (p / "docs" / "INDEX.md").exists() and (p / "docs" / "input").is_dir() and (p / "docs" / "extracted").is_dir()
    assert (p / ".gitignore").exists() and (p / ".gitattributes").exists() and not (p / ".git").exists()
    r = subprocess.run([sys.executable, "-m", "logixforge.cli", "docs", "build", str(p)], capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0 and (p / "docs" / "generated" / "ROUTINES.md").exists(), r.stdout + r.stderr
    r = subprocess.run([sys.executable, "-m", "logixforge.cli", "validate", str(p)], capture_output=True, text=True, cwd=ROOT)
    assert "DOC_SPEC" in r.stdout and "DOC_NONE" not in r.stdout          # placeholder spec flagged, docs generated
    (tmp_path / "notes.md").write_text("# Notes\nStart from HMI only.\n", encoding="utf-8")
    r = subprocess.run([sys.executable, "-m", "logixforge.cli", "docs", "ingest", str(p), str(tmp_path / "notes.md"), "--used-for", "modes"],
                       capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0 and "ingested" in r.stdout, r.stdout + r.stderr
    assert "notes.md" in (p / "docs" / "INDEX.md").read_text(encoding="utf-8")
    if shutil.which("pandoc") is None:
        r = subprocess.run([sys.executable, "-m", "logixforge.cli", "docs", "export", str(p), "--to", "docx"], capture_output=True, text=True, cwd=ROOT)
        assert r.returncode != 0 and "pandoc not found" in (r.stdout + r.stderr)


def test_docs_build_from_l5x(tmp_path):
    from logixforge.l5x.reader import read_l5x
    from logixforge.l5x.writer import write_l5x
    out = write_l5x(load_project(DEMO), str(tmp_path / "Existing.L5X"))
    written = generate_docs(read_l5x(out))
    d = tmp_path / "Existing_docs"
    assert d.is_dir() and {p.parent for p in written} == {d}
    assert "O_Conveyor01_Run | OTE | P_Conveyor/R_Outputs:0" in (d / "INTERLOCKS.md").read_text(encoding="utf-8")
    r = subprocess.run([sys.executable, "-m", "logixforge.cli", "docs", "build", out, "-o", str(tmp_path / "x")], capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0 and (tmp_path / "x" / "ROUTINES.md").exists(), r.stdout + r.stderr


def test_hmi_export_reader_and_navigation_doc():
    from logixforge.hmi.reader import read_hmi_export
    from logixforge.docs.hmi_nav import nav_from_export, reachability, hmi_navigation_markdown
    ex = read_hmi_export(ROOT / "profiles" / "alsu" / "examples" / "masterCode" / "hmi-export")
    assert ex.project_name == "masterHMI" and ex.home_screen == "HOME" and ex.controllers == ["masterCode"]
    assert "PanelView 5510" in ex.device_type and len(ex.shortcuts) == 2 and "LED_Status" in ex.aogs
    menu = ex.screen("User-Defined Screens\Menus\Menu_Main")
    assert "User-Defined Screens\Menus\Menu_Details" in menu.nav_targets and menu.banner is False
    banner = ex.screen("Predefined Screens\Banner")
    assert banner.kind == "banner" and "Navigation Menu\AlarmSummary" in banner.nav_targets
    cav = ex.screen("Cavity")
    assert "UDT_bi" in cav.aogs and any(b.startswith("masterCode.Cav1.") for b in cav.bindings)
    assert ex.screen("Config_System").security == {"Operator": "ReadOnly", "Engineer": "FullAccess"}
    nav = nav_from_export(ex)
    seen, unreachable, dangling = reachability(nav)
    assert nav.home == "User-Defined Screens\HOME" and dangling == []
    assert {u.rsplit("\\", 1)[-1] for u in unreachable} == {"LLRF_Analog_Config", "Manual", "HOME_Prev"}
    md = hmi_navigation_markdown(nav)
    assert "## Screen hierarchy" in md and "## Navigation graph" in md and "`Configuration\System1\LLRF_Analog_Config`" in md
    assert '15#quot; PanelView' not in md  # device only appears in prose here
    assert "| Config_System | User-Defined Screens\Configuration | no | Operator=ReadOnly, Engineer=FullAccess |" in md


def test_system_and_navigation_docs_from_spec(tmp_path):
    root = _copy_demo(tmp_path)
    written = {p.name for p in generate_docs(load_project(root))}
    assert {"SYSTEM.md", "HMI_NAVIGATION.md"} <= written
    gen = root / "docs" / "generated"
    sysmd = (gen / "SYSTEM.md").read_text(encoding="utf-8")
    assert "## 2. Architecture" in sysmd and "```mermaid" in sysmd and "| Controller | `ConveyorDemo` |" in sysmd
    assert "## 7. External data interface" in sysmd and "| HMI_Conveyor01 |" in sysmd
    nav = (gen / "HMI_NAVIGATION.md").read_text(encoding="utf-8")
    assert "Overview (home)" in nav and "-->|Settings|" in nav and "Unreachable screens" in nav and ": none." in nav
    assert "AOG_UDT_Motor" in nav


def test_docs_build_l5x_with_hmi_export(tmp_path):
    from logixforge.l5x.writer import write_l5x
    out = write_l5x(load_project(DEMO), str(tmp_path / "X.L5X"))
    hmi = ROOT / "profiles" / "alsu" / "examples" / "masterCode" / "hmi-export"
    r = subprocess.run([sys.executable, "-m", "logixforge.cli", "docs", "build", out, "-o", str(tmp_path / "d"), "--hmi", str(hmi)],
                       capture_output=True, text=True, cwd=ROOT)
    assert r.returncode == 0 and (tmp_path / "d" / "HMI_NAVIGATION.md").exists(), r.stdout + r.stderr
    assert "masterHMI" in (tmp_path / "d" / "SYSTEM.md").read_text(encoding="utf-8")
    r = subprocess.run([sys.executable, "-m", "logixforge.cli", "docs", "build", out, "-o", str(tmp_path / "e"), "--hmi", str(tmp_path)],
                       capture_output=True, text=True, cwd=ROOT)
    assert r.returncode != 0 and "ViewApplication.hmi missing" in (r.stdout + r.stderr)


def test_ingest_l5x_is_provenance_not_extraction(tmp_path):
    """BACKLOG 7: a Studio 5000 export indexed with --no-copy is a provenance row, not an 'unsupported format' error."""
    root = _copy_demo(tmp_path)
    exp = tmp_path / "Line.L5X"
    exp.write_text("<RSLogix5000Content/>", encoding="utf-8")
    r = ingest(root, exp, title="Studio 5000 export", copy=False)
    assert r["error"] == "" and r["extracted"] is None
    row = read_index(root)[-1]
    assert row["Kind"] == "l5x" and row["Extracted"].startswith("provenance") and "NOT EXTRACTED" not in row["Extracted"]
    assert not (root / "docs" / "extracted" / "Line.md").exists()
    with pytest.raises(RuntimeError, match="provenance"):
        extract_text(exp)
