"""Generate the project document set from the spec (docs/generated/).

Every file starts with a generated-by header carrying the spec hash; `.stamp.json` records the hash so
the validator can flag stale docs (DOC_STALE). Markdown is canonical; `lf docs export` turns it into
PDF/DOCX with pandoc when a document-control copy is needed.
"""
from __future__ import annotations

import csv
import json
import re
from collections import defaultdict
from datetime import date
from pathlib import Path

from ..hmi.docs import hmi_tags_markdown
from ..model import ATOMIC_TYPES, Project, Routine
from ..rll import RESERVED_WORDS, RungSyntaxError, base_tag, parse_rung
from .extract import spec_hash

STAMP = ".stamp.json"
OUTPUT_INSTR = {"OTE", "OTL", "OTU"}
CONDITION_INSTR = {"XIC", "XIO", "EQU", "NEQ", "GRT", "GEQ", "LES", "LEQ", "LIM", "EQ", "NE", "GT", "GE", "LT", "LE", "LIMIT",
                   "CMP", "MEQ", "ONS", "OSR", "OSF"}
IO_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(:\d+)?:[ICOS]\d?(\.|$)")
ST_ID = re.compile(r"[A-Za-z_][A-Za-z0-9_]*(?:[.\[][A-Za-z0-9_.\[\]]*)?")
ST_KEYWORDS = {"IF", "THEN", "ELSIF", "ELSE", "END_IF", "CASE", "OF", "END_CASE", "FOR", "TO", "BY", "DO", "END_FOR",
               "WHILE", "END_WHILE", "REPEAT", "UNTIL", "END_REPEAT", "AND", "OR", "XOR", "NOT", "MOD", "TRUE", "FALSE", "EXIT", "RETURN"}


def _hdr(h: str, controller: str) -> str:
    return f"<!-- generated by lf docs build from the {controller} spec (spec {h}) on {date.today().isoformat()}; do not edit, change the spec and rebuild -->\n"


def _t(cell) -> str:
    return str(cell if cell is not None else "").replace("|", "\\|").replace("\n", " ")


def _table(headers: list[str], rows: list[list]) -> list[str]:
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(_t(c) for c in r) + " |" for r in rows]
    return out + [""]


# ------------------------------------------------------------------ I/O list

def io_rows(proj: Project) -> list[list]:
    rows = []
    for t in proj.tags:
        if t.alias_for and IO_RE.match(t.alias_for):
            rows.append([t.name, "controller", t.alias_for, t.data_type or "", t.description])
    for p in proj.programs:
        for t in p.tags:
            if t.alias_for and IO_RE.match(t.alias_for):
                rows.append([t.name, p.name, t.alias_for, t.data_type or "", t.description])
    return rows


def io_list_markdown(proj: Project, h: str) -> str:
    L = [_hdr(h, proj.controller.name), f"# {proj.controller.name} - I/O list", ""]
    L += ["## Modules", ""]
    if proj.modules:
        L += _table(["Module", "Catalog", "Parent", "Address", "Description"],
                    [[m.name, m.catalog_number, m.parent, m.address, m.description] for m in proj.modules])
    else:
        L += ["(no modules in the spec yet)", ""]
    L += ["## I/O points (alias tags)", ""]
    rows = io_rows(proj)
    L += _table(["Tag", "Scope", "Module point", "Type", "Description"], rows) if rows else ["(no alias tags to module points)", ""]
    L += ["## Module tags referenced directly in logic", "",
          "Direct references bypass the input/output mapping routines; each one should be justified.", ""]
    direct = defaultdict(set)
    for p in proj.programs:
        for r in p.routines:
            for where, _out, conds, _c in interlock_rows_for(r, f"{p.name}/{r.name}"):
                for c in conds:
                    if IO_RE.match(c):
                        direct[c].add(where)
            if r.kind == "RLL":
                for rung in r.rungs:
                    for op in _all_operands(rung.text):
                        if IO_RE.match(op):
                            direct[op].add(f"{p.name}/{r.name}:{rung.number}")
    L += _table(["Module point", "Referenced in"], [[k, ", ".join(sorted(v))] for k, v in sorted(direct.items())]) if direct else ["(none)", ""]
    return "\n".join(L)


def write_io_csv(proj: Project, path: Path) -> None:
    with open(path, "w", newline="", encoding="utf-8") as f:
        wr = csv.writer(f)
        wr.writerow(["Tag", "Scope", "ModulePoint", "Type", "Description"])
        wr.writerows(io_rows(proj))


# ------------------------------------------------------------------ tags

def tags_markdown(proj: Project, h: str) -> str:
    L = [_hdr(h, proj.controller.name), f"# {proj.controller.name} - data types, AOIs and tags", ""]
    if proj.data_types:
        L += ["## User-defined data types", ""]
        for d in proj.data_types:
            L += [f"### {d.name}", "", d.description, ""] if d.description else [f"### {d.name}", ""]
            L += _table(["Member", "Type", "Dim", "Description"], [[m.name, m.data_type, m.dimension or "", m.description] for m in d.members])
    if proj.aois:
        L += ["## Add-On Instructions", ""]
        for a in proj.aois:
            L += [f"### {a.name} (rev {a.revision})", ""] + ([a.description, ""] if a.description else [])
            L += _table(["Parameter", "Usage", "Type", "Req", "Description"],
                        [[p.name, p.usage, p.data_type, "yes" if p.required else "", p.description] for p in a.parameters])
    L += ["## Controller tags", ""]
    L += _table(["Tag", "Type", "Dim", "Access", "Description"],
                [[t.name, t.data_type or f"alias {t.alias_for}", t.dimensions, t.external_access, t.description] for t in proj.tags])
    for p in proj.programs:
        if p.tags:
            L += [f"## Program tags: {p.name}", ""]
            L += _table(["Tag", "Type", "Dim", "Usage", "Description"],
                        [[t.name, t.data_type or f"alias {t.alias_for}", t.dimensions, t.usage, t.description] for t in p.tags])
    return "\n".join(L)


# ------------------------------------------------------------------ routines

def _jsr_targets(r: Routine) -> list[str]:
    out = []
    if r.kind == "RLL":
        for rung in r.rungs:
            try:
                for i in parse_rung(rung.text).walk():
                    if i.name == "JSR" and i.operands:
                        out.append(i.operands[0])
            except RungSyntaxError:
                continue
    else:
        for line in r.st_lines:
            for m in re.finditer(r"\bJSR\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)", line):
                out.append(m.group(1))
    return out


def _instr_histogram(r: Routine) -> dict[str, int]:
    hist: dict[str, int] = defaultdict(int)
    if r.kind == "RLL":
        for rung in r.rungs:
            try:
                for i in parse_rung(rung.text).walk():
                    hist[i.name] += 1
            except RungSyntaxError:
                pass
    return dict(sorted(hist.items(), key=lambda kv: (-kv[1], kv[0])))


def _mid(s: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", s)


def routines_markdown(proj: Project, h: str) -> str:
    L = [_hdr(h, proj.controller.name), f"# {proj.controller.name} - tasks, programs and routines", ""]
    L += ["## Structure", "", "```mermaid", "flowchart LR", f"  C[{proj.controller.name}<br/>{proj.controller.processor_type} v{proj.controller.major_rev}]"]
    for t in proj.tasks:
        rate = f" {t.rate_ms} ms" if t.kind == "PERIODIC" else ""
        L.append(f"  C --> T_{_mid(t.name)}[/{t.name}<br/>{t.kind}{rate}/]")
        for pn in t.programs:
            L.append(f"  T_{_mid(t.name)} --> P_{_mid(pn)}[{pn}]")
            p = proj.find_program(pn)
            if p:
                for r in p.routines:
                    L.append(f"  P_{_mid(pn)} --> R_{_mid(pn)}_{_mid(r.name)}({r.name})")
    L += ["```", ""]
    L += ["## Tasks", ""]
    L += _table(["Task", "Type", "Rate ms", "Priority", "Watchdog ms", "Programs", "Description"],
                [[t.name, t.kind, t.rate_ms or "", t.priority, t.watchdog_ms, ", ".join(t.programs), t.description] for t in proj.tasks])
    for p in proj.programs:
        L += [f"## Program {p.name}", ""] + ([p.description, ""] if p.description else [])
        L += [f"Main routine `{p.main_routine}`" + (f", fault routine `{p.fault_routine}`" if p.fault_routine else "") + ".", ""]
        rows = []
        for r in p.routines:
            size = f"{len(r.rungs)} rungs" if r.kind == "RLL" else f"{len(r.st_lines)} lines"
            rows.append([r.name, r.kind, size, ", ".join(_jsr_targets(r)) or "", r.description])
        L += _table(["Routine", "Language", "Size", "Calls", "Description"], rows)
        calls = [(r.name, tgt) for r in p.routines for tgt in _jsr_targets(r)]
        if calls:
            L += ["```mermaid", "flowchart TD"]
            L += [f"  {_mid(a)}({a}) --> {_mid(b)}({b})" for a, b in calls]
            L += ["```", ""]
        for r in p.routines:
            if r.kind == "RLL" and r.rungs:
                L += [f"### {r.name} rung index", ""]
                L += _table(["Rung", "Comment", "Instructions"],
                            [[rung.number, rung.comment.splitlines()[0] if rung.comment else "", " ".join(sorted(set(_instr_names(rung.text))))] for rung in r.rungs])
    if proj.aois:
        L += ["## Add-On Instruction logic", ""]
        L += _table(["AOI", "Routine", "Language", "Size", "Description"],
                    [[a.name, r.name, r.kind, f"{len(r.rungs)} rungs" if r.kind == "RLL" else f"{len(r.st_lines)} lines", r.description]
                     for a in proj.aois for r in a.routines])
    return "\n".join(L)


def _instr_names(text: str) -> list[str]:
    try:
        return [i.name for i in parse_rung(text).walk()]
    except RungSyntaxError:
        return []


def _all_operands(text: str) -> list[str]:
    try:
        return [op for i in parse_rung(text).walk() for op in i.operands if op and not op.startswith("?")]
    except RungSyntaxError:
        return []


# ------------------------------------------------------------------ interlocks (cause and effect)

def _rll_interlocks(r: Routine, where: str):
    for rung in r.rungs:
        try:
            parsed = parse_rung(rung.text)
        except RungSyntaxError:
            continue
        conds, outs = [], []
        for i in parsed.walk():
            if i.name in OUTPUT_INSTR and i.operands:
                outs.append((i.name, i.operands[0]))
            elif i.name in CONDITION_INSTR:
                for op in i.operands:
                    if op and not op.startswith("?") and not re.match(r"^-?\d|^'|^16#", op):
                        conds.append(("~" if i.name == "XIO" else "") + op)
            elif i.is_aoi or i.name in {"TON", "TOF", "RTO", "CTU", "CTD", "MOV", "MOVE", "COP", "CPS"}:
                # AOI/timer/move operands are effects as well as causes; keep the first operand as a cause
                if i.operands and i.operands[0] and not i.operands[0].startswith("?"):
                    conds.append(i.operands[0])
        for kind, out in outs:
            yield (f"{where}:{rung.number}", f"{kind} {out}", [c for c in conds if c.lstrip('~') != out], rung.comment.splitlines()[0] if rung.comment else "")


_ST_NOT_ID = re.compile(r"(NOT\s+)?(" + ST_ID.pattern + ")", re.IGNORECASE)


def _st_ids(expr: str) -> list[str]:
    """Identifiers in an ST expression; `NOT X` becomes `~X` (same notation as XIO in ladder)."""
    out = []
    for m in _ST_NOT_ID.finditer(re.sub(r"'[^']*'", "", expr)):
        ident = m.group(2)
        if ident.split(".")[0].split("[")[0].upper() in ST_KEYWORDS | RESERVED_WORDS or re.match(r"^\d", ident):
            continue
        out.append(("~" if m.group(1) else "") + ident)
    return out


def _st_interlocks(r: Routine, where: str):
    stack: list[list[str]] = []
    for n, raw in enumerate(r.st_lines, 1):
        line = re.sub(r"//.*|\(\*.*?\*\)|/\*.*?\*/", "", raw).strip()
        if not line:
            continue
        up = line.upper()
        if up.startswith(("IF ", "IF(")) and "THEN" in up:
            stack.append(_st_ids(line[2:up.index("THEN")]))
        elif up.startswith("ELSIF"):
            if stack:
                stack[-1] = _st_ids(line[5:up.index("THEN")] if "THEN" in up else line[5:])
        elif up.startswith("ELSE"):
            if stack:
                stack[-1] = ["~(" + " ".join(stack[-1]) + ")"] if stack[-1] else []
        elif up.startswith(("WHILE ", "CASE ", "FOR ", "REPEAT")):
            stack.append(_st_ids(line.split(" ", 1)[1]) if " " in line else [])
        elif up.startswith(("END_IF", "END_WHILE", "END_CASE", "END_FOR", "END_REPEAT")):
            if stack:
                stack.pop()
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_.\[\]]*)\s*:=\s*(.+?);?$", line)
        if m:
            conds = [c for lvl in stack for c in lvl] + _st_ids(m.group(2))
            yield (f"{where}:{n}", f":= {m.group(1)}", [c for c in conds if c.lstrip("~") != m.group(1)], "")


def interlock_rows_for(r: Routine, where: str):
    if r.kind == "RLL":
        yield from _rll_interlocks(r, where)
    elif r.kind == "ST":
        yield from _st_interlocks(r, where)


def interlocks_markdown(proj: Project, h: str) -> str:
    L = [_hdr(h, proj.controller.name), f"# {proj.controller.name} - cause and effect (derived from logic)", "",
         "For every written tag: where it is written and the conditions on that rung/statement (`~` = XIO / normally closed). "
         "Derived mechanically from the routines; it documents what the code does, not what the specification requires. "
         "Compare against SPEC.md interlock tables during review.", ""]
    by_out: dict[str, list] = defaultdict(list)
    for p in proj.programs:
        for r in p.routines:
            for where, out, conds, comment in interlock_rows_for(r, f"{p.name}/{r.name}"):
                by_out[out.split(" ", 1)[1]].append((where, out.split(" ", 1)[0], conds, comment))
    multi = {k: v for k, v in by_out.items() if len({w for w, *_ in v}) > 1}
    if multi:
        L += ["## Tags written in more than one place", "",
              "Multiple writers of one output are a review finding unless they are OTL/OTU pairs or intentionally sequential.", ""]
        L += _table(["Tag", "Writers"], [[k, ", ".join(f"{w} ({k2})" for w, k2, *_ in v)] for k, v in sorted(multi.items())])
    L += ["## Cause and effect", ""]
    rows = []
    for out in sorted(by_out):
        for where, kind, conds, comment in by_out[out]:
            rows.append([out, kind, where, ", ".join(dict.fromkeys(conds)) or "(unconditional)", comment])
    L += _table(["Effect (tag)", "Via", "Where", "Causes / conditions", "Rung comment"], rows) if rows else ["(no writes found)", ""]
    for a in proj.aois:
        rows = []
        for r in a.routines:
            for where, out, conds, comment in interlock_rows_for(r, f"AOI {a.name}/{r.name}"):
                rows.append([out.split(" ", 1)[1], out.split(" ", 1)[0], where, ", ".join(dict.fromkeys(conds)) or "(unconditional)", comment])
        if rows:
            L += [f"## AOI {a.name}", ""] + _table(["Effect", "Via", "Where", "Causes / conditions", "Comment"], rows)
    return "\n".join(L)


# ------------------------------------------------------------------ test plan

def test_plan_markdown(proj: Project, h: str) -> str:
    L = [_hdr(h, proj.controller.name), f"# {proj.controller.name} - test plan", "",
         "Skeleton derived from the spec: one case per alarm, per physical output and per HMI screen. "
         "Fill Expected/Result during FAT/SAT (Emulate or bench). Add sequence tests from SPEC.md by hand in the last section.", "",
         "| # | Case | Stimulus | Expected | Result | Tester / date |", "|---|---|---|---|---|---|"]
    n = 0
    def _is_output(t):
        return (t.alias_for and IO_RE.match(t.alias_for) and ":O" in t.alias_for) or re.match(r"^(O|DO|AO|Q)_", t.name)
    outs = [t for t in proj.tags if _is_output(t)] + [t for p in proj.programs for t in p.tags if _is_output(t)]
    for t in outs:
        n += 1
        L.append(f"| {n} | Output {t.name} | drive the permissives per SPEC.md; then remove each one | output on only with all permissives; drops on each removal | | |")
    for a in proj.alarms:
        n += 1
        L.append(f"| {n} | Alarm {a.name} | force `{a.input_path}` {a.condition}{' (delay ' + str(a.on_delay_ms) + ' ms)' if a.on_delay_ms else ''} | alarm shown: \"{a.message}\" sev {a.severity}; {'ack required; ' if a.ack_required else ''}{'latched until reset' if a.latched else 'clears when input returns'} | | |")
    try:
        from ..hmi.spec import load_hmi_spec
        spec = load_hmi_spec(proj)
    except Exception:  # noqa: BLE001 - docs must never fail on HMI spec problems
        spec = None
    if spec:
        for s in spec.screens:
            n += 1
            L.append(f"| {n} | HMI screen {s.name} | open the screen; exercise every button/input | values track the controller; commands write the bound tags | | |")
    L += ["", "## Sequence and mode tests (from SPEC.md)", "", "| # | Case | Stimulus | Expected | Result | Tester / date |", "|---|---|---|---|---|---|", ""]
    return "\n".join(L)


# ------------------------------------------------------------------ driver

def readme_markdown(proj: Project, h: str, files: list[str]) -> str:
    L = [_hdr(h, proj.controller.name), f"# {proj.controller.name} - generated documents", "",
         f"Controller `{proj.controller.name}` ({proj.controller.processor_type}, Logix v{proj.controller.major_rev}). "
         f"{len(proj.data_types)} UDTs, {len(proj.aois)} AOIs, {len(proj.modules)} modules, {len(proj.tags)} controller tags, "
         f"{len(proj.programs)} programs, {len(proj.tasks)} tasks, {len(proj.alarms)} alarms.", "",
         "| File | Content |", "|---|---|"]
    desc = {"IO_LIST.md": "modules, I/O alias tags, direct module references", "IO_LIST.csv": "I/O points for spreadsheets",
            "TAGS.md": "UDTs, AOI interfaces, controller and program tags", "ROUTINES.md": "task/program/routine tree, call graph, rung index",
            "INTERLOCKS.md": "cause and effect derived from the logic, multiple-writer check", "ALARMS.csv": "tag-based alarm list",
            "HMI_TAGS.md": "HMI tag interface and alarm summary", "TEST_PLAN.md": "FAT/SAT checklist skeleton"}
    L += [f"| {f} | {desc.get(f, '')} |" for f in files if f != "README.md"]
    L += ["", "Regenerate with `lf docs build <project>`; export with `lf docs export <project> --to pdf|docx`.", ""]
    return "\n".join(L)


def generate_docs(proj: Project, out_dir: str | Path | None = None) -> list[Path]:
    """Write the document set. `proj.source_dir` is a spec directory (-> docs/generated/) or an .L5X file
    (existing project: -> <stem>_docs/ next to it unless `out_dir` is given; the hash is the file's)."""
    root = Path(proj.source_dir)
    if root.is_file():
        import hashlib
        d = Path(out_dir) if out_dir else root.with_name(root.stem + "_docs")
        h = hashlib.sha256(root.read_bytes()).hexdigest()[:16]
    else:
        d = Path(out_dir) if out_dir else root / "docs" / "generated"
        h = spec_hash(root) if root.is_dir() else "n/a"
    d.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    def put(name: str, text: str):
        p = d / name
        p.write_text(text, encoding="utf-8")
        written.append(p)

    put("IO_LIST.md", io_list_markdown(proj, h))
    write_io_csv(proj, d / "IO_LIST.csv"); written.append(d / "IO_LIST.csv")
    put("TAGS.md", tags_markdown(proj, h))
    put("ROUTINES.md", routines_markdown(proj, h))
    put("INTERLOCKS.md", interlocks_markdown(proj, h))
    put("HMI_TAGS.md", _hdr(h, proj.controller.name) + hmi_tags_markdown(proj))
    if proj.alarms:
        p = d / "ALARMS.csv"
        with open(p, "w", newline="", encoding="utf-8") as f:
            wr = csv.writer(f)
            wr.writerow(["Name", "Input", "Condition", "Severity", "Class", "Group", "Latched", "AckRequired", "OnDelay_ms", "Message"])
            for a in proj.alarms:
                wr.writerow([a.name, a.input_path, a.condition, a.severity, a.alarm_class, a.hmi_group, a.latched, a.ack_required, a.on_delay_ms, a.message])
        written.append(p)
    put("TEST_PLAN.md", test_plan_markdown(proj, h))
    names = [w.name for w in written]
    put("README.md", readme_markdown(proj, h, names))
    (d / STAMP).write_text(json.dumps({"spec_hash": h, "generated": date.today().isoformat(), "controller": proj.controller.name,
                                       "files": names + ["README.md"]}, indent=2), encoding="utf-8")
    return written


def is_stale(root: str | Path) -> bool | None:
    """True if docs/generated/.stamp.json exists and its hash differs from the spec; None if never generated."""
    st = Path(root) / "docs" / "generated" / STAMP
    if not st.exists():
        return None
    try:
        return json.loads(st.read_text(encoding="utf-8")).get("spec_hash") != spec_hash(root)
    except (ValueError, OSError):
        return True
