
// System


Calibration_AOI(Calibration_System[0], Main_LCWS_Temp);


Calibration_AOI(Calibration_System[1], Main_LCWR_Temp);


Calibration_AOI(Calibration_System[2], Main_LCWS_Pressure);


Calibration_AOI(Calibration_System[3], Main_LCWR_Pressure);





// Feeder 1


Calibration_AOI(Calibration_Feeder1[0], Feeder1.Circ_LCWR_Flow);


//Calibration_AOI(Calibration_Feeder1[1], Feeder1.Circ_LCWR_Temp);


Calibration_AOI(Calibration_Feeder1[2], Feeder1.CircLoad_LCWR_Flow);


//Calibration_AOI(Calibration_Feeder1[3], Feeder1.CircLoad_LCWR_Temp);


Calibration_AOI(Calibration_Feeder1[4], Feeder1.DummyLoad_LCWR_Flow);


//Calibration_AOI(Calibration_Feeder1[5], Feeder1.DummyLoad_LCWR_Temp);





// Feeder 2


Calibration_AOI(Calibration_Feeder2[0], Feeder2.Circ_LCWR_Flow);


//Calibration_AOI(Calibration_Feeder2[1], Feeder2.Circ_LCWR_Temp);


Calibration_AOI(Calibration_Feeder2[2], Feeder2.CircLoad_LCWR_Flow);


//Calibration_AOI(Calibration_Feeder2[3], Feeder2.CircLoad_LCWR_Temp);


Calibration_AOI(Calibration_Feeder2[4], Feeder2.DummyLoad_LCWR_Flow);


//Calibration_AOI(Calibration_Feeder2[5], Feeder2.DummyLoad_LCWR_Temp);





// Cavity 1


Calibration_AOI(Calibration_Cav1[0], Cav1.LCWR_Temp[0]);


Calibration_AOI(Calibration_Cav1[1], Cav1.LCWR_Temp[1]);


Calibration_AOI(Calibration_Cav1[2], Cav1.LCWR_Temp[2]);


Calibration_AOI(Calibration_Cav1[3], Cav1.LCWR_Temp[3]);


Calibration_AOI(Calibration_Cav1[4], Cav1.LCWR_Temp[4]);


Calibration_AOI(Calibration_Cav1[5], Cav1.LCWR_Temp[5]);


Calibration_AOI(Calibration_Cav1[6], Cav1.LCWR_Temp[6]);


Calibration_AOI(Calibration_Cav1[7], Cav1.LCWR_Temp[7]);


Calibration_AOI(Calibration_Cav1[8], Cav1.LCWR_Temp[8]);


Calibration_AOI(Calibration_Cav1[9], Cav1.LCWR_Temp[9]);


Calibration_AOI(Calibration_Cav1[10], Cav1.LCWR_Temp[10]);


Calibration_AOI(Calibration_Cav1[11], Cav1.LCWR_Temp[11]);


Calibration_AOI(Calibration_Cav1[12], Cav1.LCWR_Temp[12]);


Calibration_AOI(Calibration_Cav1[13], Cav1.LCWR_Temp[13]);


Calibration_AOI(Calibration_Cav1[14], Cav1.LCWR_Temp[14]);


Calibration_AOI(Calibration_Cav1[15], Cav1.LCWR_Flow[0]);


Calibration_AOI(Calibration_Cav1[16], Cav1.LCWR_Flow[1]);


Calibration_AOI(Calibration_Cav1[17], Cav1.LCWR_Flow[2]);


Calibration_AOI(Calibration_Cav1[18], Cav1.LCWR_Flow[3]);


Calibration_AOI(Calibration_Cav1[19], Cav1.LCWR_Flow[4]);


Calibration_AOI(Calibration_Cav1[20], Cav1.LCWR_Flow[5]);


Calibration_AOI(Calibration_Cav1[21], Cav1.LCWR_Flow[6]);


Calibration_AOI(Calibration_Cav1[22], Cav1.LCWR_Flow[7]);


Calibration_AOI(Calibration_Cav1[23], Cav1.LCWR_Flow[8]);


Calibration_AOI(Calibration_Cav1[24], Cav1.LCWR_Flow[9]);


Calibration_AOI(Calibration_Cav1[25], Cav1.LCWR_Flow[10]);


Calibration_AOI(Calibration_Cav1[26], Cav1.LCWR_Flow[11]);


Calibration_AOI(Calibration_Cav1[27], Cav1.LCWR_Flow[12]);


Calibration_AOI(Calibration_Cav1[28], Cav1.LCWR_Flow[13]);


Calibration_AOI(Calibration_Cav1[29], Cav1.LCWR_Flow[14]);


Calibration_AOI(Calibration_Cav1[30], Cav1.Surf_Temp[0]);


Calibration_AOI(Calibration_Cav1[31], Cav1.Surf_Temp[1]);


Calibration_AOI(Calibration_Cav1[32], Cav1.Surf_Temp[2]);


Calibration_AOI(Calibration_Cav1[33], Cav1.Surf_Temp[3]);


Calibration_AOI(Calibration_Cav1[34], Cav1.Surf_Temp[4]);


Calibration_AOI(Calibration_Cav1[35], Cav1.Surf_Temp[5]);


Calibration_AOI(Calibration_Cav1[36], Cav1.Surf_Temp[6]);


Calibration_AOI(Calibration_Cav1[37], Cav1.Surf_Temp[7]);


Calibration_AOI(Calibration_Cav1[38], Cav1.Surf_Temp[8]);


Calibration_AOI(Calibration_Cav1[39], Cav1.CouplerTemp);





// Cavity 2


Calibration_AOI(Calibration_Cav2[0], Cav2.LCWR_Temp[0]);


Calibration_AOI(Calibration_Cav2[1], Cav2.LCWR_Temp[1]);


Calibration_AOI(Calibration_Cav2[2], Cav2.LCWR_Temp[2]);


Calibration_AOI(Calibration_Cav2[3], Cav2.LCWR_Temp[3]);


Calibration_AOI(Calibration_Cav2[4], Cav2.LCWR_Temp[4]);


Calibration_AOI(Calibration_Cav2[5], Cav2.LCWR_Temp[5]);


Calibration_AOI(Calibration_Cav2[6], Cav2.LCWR_Temp[6]);


Calibration_AOI(Calibration_Cav2[7], Cav2.LCWR_Temp[7]);


Calibration_AOI(Calibration_Cav2[8], Cav2.LCWR_Temp[8]);


Calibration_AOI(Calibration_Cav2[9], Cav2.LCWR_Temp[9]);


Calibration_AOI(Calibration_Cav2[10], Cav2.LCWR_Temp[10]);


Calibration_AOI(Calibration_Cav2[11], Cav2.LCWR_Temp[11]);


Calibration_AOI(Calibration_Cav2[12], Cav2.LCWR_Temp[12]);


Calibration_AOI(Calibration_Cav2[13], Cav2.LCWR_Temp[13]);


Calibration_AOI(Calibration_Cav2[14], Cav2.LCWR_Temp[14]);


Calibration_AOI(Calibration_Cav2[15], Cav2.LCWR_Flow[0]);


Calibration_AOI(Calibration_Cav2[16], Cav2.LCWR_Flow[1]);


Calibration_AOI(Calibration_Cav2[17], Cav2.LCWR_Flow[2]);


Calibration_AOI(Calibration_Cav2[18], Cav2.LCWR_Flow[3]);


Calibration_AOI(Calibration_Cav2[19], Cav2.LCWR_Flow[4]);


Calibration_AOI(Calibration_Cav2[20], Cav2.LCWR_Flow[5]);


Calibration_AOI(Calibration_Cav2[21], Cav2.LCWR_Flow[6]);


Calibration_AOI(Calibration_Cav2[22], Cav2.LCWR_Flow[7]);


Calibration_AOI(Calibration_Cav2[23], Cav2.LCWR_Flow[8]);


Calibration_AOI(Calibration_Cav2[24], Cav2.LCWR_Flow[9]);


Calibration_AOI(Calibration_Cav2[25], Cav2.LCWR_Flow[10]);


Calibration_AOI(Calibration_Cav2[26], Cav2.LCWR_Flow[11]);


Calibration_AOI(Calibration_Cav2[27], Cav2.LCWR_Flow[12]);


Calibration_AOI(Calibration_Cav2[28], Cav2.LCWR_Flow[13]);


Calibration_AOI(Calibration_Cav2[29], Cav2.LCWR_Flow[14]);


Calibration_AOI(Calibration_Cav2[30], Cav2.Surf_Temp[0]);


Calibration_AOI(Calibration_Cav2[31], Cav2.Surf_Temp[1]);


Calibration_AOI(Calibration_Cav2[32], Cav2.Surf_Temp[2]);


Calibration_AOI(Calibration_Cav2[33], Cav2.Surf_Temp[3]);


Calibration_AOI(Calibration_Cav2[34], Cav2.Surf_Temp[4]);


Calibration_AOI(Calibration_Cav2[35], Cav2.Surf_Temp[5]);


Calibration_AOI(Calibration_Cav2[36], Cav2.Surf_Temp[6]);


Calibration_AOI(Calibration_Cav2[37], Cav2.Surf_Temp[7]);


Calibration_AOI(Calibration_Cav2[38], Cav2.Surf_Temp[8]);


Calibration_AOI(Calibration_Cav2[39], Cav2.CouplerTemp);






