"""lf - LogixForge command line.

  lf init <dir> --name CTRL [--processor 1756-L83E] [--rev 33]
  lf validate <project_dir | file.L5X> [--json] [--strict]
  lf build <project_dir> [-o out.L5X]
  lf partial <project_dir> --kind Routine|Program|Tag|DataType|AddOnInstructionDefinition --name X [--program P] -o out.L5X
  lf inspect <file.L5X> [--json] [--routine PROGRAM/ROUTINE]
  lf decompile <file.L5X> -o <project_dir>      # L5X -> editable spec (round-trip / review of uploads)
  lf diff <a.L5X|dir> <b.L5X|dir>
  lf rung check "<rung text>"
  lf docs build <project_dir | file.L5X> # spec -> docs/generated/ (I/O list, tags, routines, interlocks, alarms, HMI, test plan);
                                         # an .L5X export of an existing project -> <stem>_docs/ (or -o)
  lf docs ingest <project_dir> <file>... # given documents -> docs/input/ + docs/extracted/*.md + docs/INDEX.md
  lf docs export <project_dir> --to pdf|docx|html   (pandoc)
  lf online ...  (pycomm3)         lf sdk ...  (Logix Designer SDK)

All subcommands exit non-zero on error so hooks/agents can rely on them.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from . import __version__
from .l5x.reader import export_project_dir, read_l5x
from .l5x.writer import project_summary, write_l5x, write_partial
from .model import Project
from .project import SpecError, load_project
from .rll import RungSyntaxError, instruction_names, operand_tags, parse_rung
from .validate import Finding, has_errors, validate


def _load_any(path: str) -> Project:
    p = Path(path)
    if p.is_dir():
        return load_project(p)
    if p.suffix.lower() == ".l5x":
        return read_l5x(p)
    raise SpecError(f"{path}: expected a project directory or .L5X file")


def _naming_rules(proj_dir: str | None) -> dict:
    """Optional house naming patterns from <project>/naming.json or LOGIXFORGE_NAMING env var."""
    for cand in ([Path(proj_dir) / "naming.json"] if proj_dir else []) + [Path(os.environ.get("LOGIXFORGE_NAMING", ""))]:
        if cand and cand.is_file():
            return json.loads(cand.read_text(encoding="utf-8"))
    return {}


def _print_findings(findings: list[Finding], as_json: bool) -> None:
    if as_json:
        print(json.dumps([f.__dict__ for f in findings], indent=2))
        return
    for f in findings:
        print(f)
    n_err = sum(1 for f in findings if f.level == "error")
    n_warn = sum(1 for f in findings if f.level == "warning")
    print(f"\n{n_err} error(s), {n_warn} warning(s), {len(findings) - n_err - n_warn} info")


# ---------------------------------------------------------------- commands

PROFILES_DIR = Path(__file__).resolve().parents[1] / "profiles"


def _apply_profile(root: Path, name: str) -> list[str]:
    """Copy a site profile's naming.json and templates/ into a project. Returns copied paths."""
    import shutil
    pdir = PROFILES_DIR / name
    if not pdir.is_dir():
        sys.exit(f"profile {name!r} not found; available: {sorted(p.name for p in PROFILES_DIR.iterdir() if p.is_dir())}")
    copied = []
    nj = pdir / "naming.json"
    if nj.exists():
        shutil.copy(nj, root / "naming.json")
        copied.append("naming.json")
    tdir = pdir / "templates"
    if tdir.is_dir():
        for src in tdir.rglob("*"):
            if src.is_file() and src.name != "README.md":
                dst = root / src.relative_to(tdir)
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy(src, dst)
                copied.append(str(src.relative_to(tdir)))
    (root / "profile.json").write_text(json.dumps({"profile": name}, indent=2), encoding="utf-8")
    return copied


def cmd_init(a):
    root = Path(a.dir)
    if (root / "controller.json").exists() and not a.force:
        sys.exit(f"{root} already contains controller.json (use --force)")
    sk = {"task": {"name": "MainTask", "kind": "CONTINUOUS", "priority": 10, "watchdog_ms": 500},
          "program": "MainProgram", "main_routine": "MainRoutine", "first_routine": "",
          "controller_description": "{name} - generated by LogixForge"}
    if a.profile:
        skf = PROFILES_DIR / a.profile / "skeleton.json"
        if skf.exists():
            sk.update(json.loads(skf.read_text(encoding="utf-8")))
    prog, main = sk["program"], sk["main_routine"]
    for d in ["datatypes", "tags", f"programs/{prog}/routines", "aois", "modules", "docs/input", "docs/extracted", "tests"]:
        (root / d).mkdir(parents=True, exist_ok=True)
    (root / "controller.json").write_text(json.dumps({
        "name": a.name, "processor_type": a.processor, "major_rev": a.rev, "minor_rev": 11,
        "software_revision": f"{a.rev}.00", "description": sk["controller_description"].format(name=a.name),
        "chassis_size": 10, "slot": 0}, indent=2), encoding="utf-8")
    (root / f"programs/{prog}/program.json").write_text(json.dumps({
        "name": prog, "main_routine": main, "description": "Main program"}, indent=2), encoding="utf-8")
    (root / f"programs/{prog}/tags.json").write_text("[]\n", encoding="utf-8")
    first = sk.get("first_routine") or ""
    body = f"//! Main routine: calls sub-routines in scan order\n// I/O buffering first (inputs snapshot), then control\nJSR({first},0);\n" if first \
        else "//! Main routine: calls sub-routines in scan order\n// Placeholder rung - replace with JSR calls\nNOP();\n"
    (root / f"programs/{prog}/routines/{main}.rll").write_text(body, encoding="utf-8")
    if first:
        (root / f"programs/{prog}/routines/{first}.rll").write_text(
            "//! Input buffering: copy module data to R##S##xx buffer tags (or call DIAG_ AOIs) before control logic\nNOP();\n", encoding="utf-8")
    (root / "tags/controller.json").write_text("[]\n", encoding="utf-8")
    task = dict(sk["task"]); task["programs"] = [prog]
    (root / "tasks.json").write_text(json.dumps([task], indent=2), encoding="utf-8")
    (root / "naming.json").write_text(json.dumps({
        "_comment": "Optional regex per kind: tag, udt, aoi, program, routine, task, member, parameter, local",
        "udt": "^UDT_[A-Za-z0-9_]+$", "aoi": "^AOI_[A-Za-z0-9_]+$"}, indent=2), encoding="utf-8")
    (root / "docs/SPEC.md").write_text(f"# {a.name} - Functional Specification\n\n(Describe the machine/process, I/O, modes, sequences, interlocks, alarms.)\n", encoding="utf-8")
    from .docs.extract import write_index
    write_index(root, [], name=a.name)
    _write_repo_files(root)
    if a.profile:
        copied = _apply_profile(root, a.profile)
        print(f"applied profile {a.profile}: {', '.join(copied) or 'no files'}")
    if a.git:
        import subprocess
        if (root / ".git").exists():
            print("git repository already present")
        else:
            r = subprocess.run(["git", "init", "-q", str(root)], capture_output=True, text=True)
            print("initialised git repository" if r.returncode == 0 else f"git init failed: {r.stderr.strip()}")
    print(f"initialised LogixForge project in {root}")


PROJECT_GITIGNORE = """# LogixForge project - the spec is the source of truth; build output is generated
build/
__pycache__/
*.pyc
.pytest_cache/
# Studio 5000 working files (keep the .ACD in Rockwell's document system or Git LFS, not here, unless required)
*.ACD
*.Sem
*.Wrk
*.bak
*.mer
"""
PROJECT_GITATTRIBUTES = """* text=auto eol=lf
*.L5X text eol=crlf
*.hmi text eol=crlf
*.pdf binary
*.docx binary
*.xlsx binary
*.png binary
*.jpg binary
*.dwg binary
*.ACD binary
"""


def _write_repo_files(root: Path) -> None:
    """Per-project .gitignore / .gitattributes (one repository per PLC project; see plc-documentation skill)."""
    for name, body in ((".gitignore", PROJECT_GITIGNORE), (".gitattributes", PROJECT_GITATTRIBUTES)):
        p = root / name
        if not p.exists():
            p.write_text(body, encoding="utf-8")


def cmd_validate(a):
    proj = _load_any(a.path)
    findings = validate(proj, _naming_rules(a.path if Path(a.path).is_dir() else None))
    if a.strict:
        findings = [Finding("error", f.code, f.where, f.message) if f.level == "warning" else f for f in findings]
    _print_findings(findings, a.json)
    sys.exit(1 if has_errors(findings) else 0)


def cmd_build(a):
    proj = load_project(a.project)
    findings = validate(proj, _naming_rules(a.project))
    errs = [f for f in findings if f.level == "error"]
    if errs and not a.force:
        for f in errs:
            print(f, file=sys.stderr)
        sys.exit(f"build aborted: {len(errs)} error(s). Use --force to write anyway.")
    out = a.output or str(Path(a.project) / "build" / f"{proj.controller.name}.L5X")
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    write_l5x(proj, out)
    print(f"wrote {out}")
    if a.partials:
        pdir = Path(out).parent / "partial"
        pdir.mkdir(exist_ok=True)
        for d in proj.data_types:
            write_partial(proj, "DataType", d.name, str(pdir / f"DataType_{d.name}.L5X"))
        for x in proj.aois:
            write_partial(proj, "AddOnInstructionDefinition", x.name, str(pdir / f"AOI_{x.name}.L5X"))
        for p in proj.programs:
            write_partial(proj, "Program", p.name, str(pdir / f"Program_{p.name}.L5X"))
            for r in p.routines:
                write_partial(proj, "Routine", r.name, str(pdir / f"Routine_{p.name}_{r.name}.L5X"), program=p.name)
        print(f"wrote partial import files to {pdir}")
    if [f for f in findings if f.level == "warning"]:
        print(f"{sum(1 for f in findings if f.level == 'warning')} warning(s); run `lf validate {a.project}` for details")


def cmd_partial(a):
    proj = load_project(a.project)
    out = a.output or str(Path(a.project) / "build" / "partial" / f"{a.kind}_{a.name}.L5X")
    Path(out).parent.mkdir(parents=True, exist_ok=True)
    write_partial(proj, a.kind, a.name, out, program=a.program or "")
    print(f"wrote {out}")


def cmd_inspect(a):
    proj = _load_any(a.path)
    if a.routine:
        pname, _, rname = a.routine.partition("/")
        p = proj.find_program(pname)
        if not p:
            sys.exit(f"program {pname!r} not found")
        r = next((x for x in p.routines if x.name.lower() == rname.lower()), None)
        if not r:
            sys.exit(f"routine {rname!r} not found in {pname}")
        if r.kind == "RLL":
            for rung in r.rungs:
                if rung.comment:
                    print("\n".join("// " + l for l in rung.comment.splitlines()))
                print(f"{rung.number:4}: {rung.text}")
        else:
            print("\n".join(r.st_lines))
        return
    s = project_summary(proj)
    if a.json:
        print(json.dumps(s, indent=2))
    else:
        print(f"Controller {s['controller']} ({s['processor']})")
        print(f"  data types : {', '.join(s['data_types']) or '-'}")
        print(f"  AOIs       : {', '.join(s['aois']) or '-'}")
        print(f"  modules    : {', '.join(s['modules']) or '-'}")
        print(f"  ctrl tags  : {s['controller_tags']}")
        for pn, p in s["programs"].items():
            print(f"  program {pn} (main={p['main']}, tags={p['tags']})")
            for rn, size in p["routines"].items():
                print(f"     routine {rn}: {size} rungs/lines")
        for tn, t in s["tasks"].items():
            print(f"  task {tn}: {t['type']} rate={t['rate_ms']} programs={t['programs']}")


def cmd_decompile(a):
    proj = read_l5x(a.l5x)
    out = export_project_dir(proj, a.output)
    print(f"wrote project spec to {out}")


def cmd_diff(a):
    pa, pb = _load_any(a.a), _load_any(a.b)
    changes = []

    def routines(p: Project):
        d = {}
        for prog in p.programs:
            for r in prog.routines:
                d[f"{prog.name}/{r.name}"] = [x.text for x in r.rungs] if r.kind == "RLL" else r.st_lines
        for aoi in p.aois:
            for r in aoi.routines:
                d[f"AOI:{aoi.name}/{r.name}"] = [x.text for x in r.rungs] if r.kind == "RLL" else r.st_lines
        return d

    def tags(p: Project):
        d = {f"ctrl/{t.name}": (t.data_type or t.alias_for, t.dimensions) for t in p.tags}
        for prog in p.programs:
            d.update({f"{prog.name}/{t.name}": (t.data_type or t.alias_for, t.dimensions) for t in prog.tags})
        return d

    ra, rb = routines(pa), routines(pb)
    for k in sorted(set(ra) | set(rb)):
        if k not in ra:
            changes.append(f"+ routine {k}")
        elif k not in rb:
            changes.append(f"- routine {k}")
        elif ra[k] != rb[k]:
            import difflib
            changes.append(f"~ routine {k}")
            for line in difflib.unified_diff(ra[k], rb[k], lineterm="", n=1):
                if line.startswith(("---", "+++")):
                    continue
                changes.append("    " + line)
    ta, tb = tags(pa), tags(pb)
    for k in sorted(set(ta) | set(tb)):
        if k not in ta:
            changes.append(f"+ tag {k} {tb[k]}")
        elif k not in tb:
            changes.append(f"- tag {k} {ta[k]}")
        elif ta[k] != tb[k]:
            changes.append(f"~ tag {k} {ta[k]} -> {tb[k]}")
    for k in sorted({d.name for d in pa.data_types} ^ {d.name for d in pb.data_types}):
        changes.append(("- " if any(d.name == k for d in pa.data_types) else "+ ") + f"datatype {k}")
    print("\n".join(changes) if changes else "no differences")


def cmd_rung(a):
    try:
        parsed = parse_rung(a.text)
    except RungSyntaxError as e:
        sys.exit(f"syntax error: {e}")
    print("instructions:", ", ".join(instruction_names(a.text)))
    print("tags:", ", ".join(operand_tags(a.text)))
    print("ok")


def cmd_docs(a):
    from .docs.extract import ingest
    from .docs.export import project_export
    from .docs.generate import generate_docs
    if a.op == "build":
        proj = _load_any(a.project)          # spec directory, or an .L5X export of an existing project
        for p in generate_docs(proj, a.output):
            print(f"wrote {p}")
        return
    if a.op == "ingest":
        if not a.files:
            sys.exit("lf docs ingest <project> <file>... [--title T --doc-no N --rev R --date D --used-for X]")
        for f in a.files:
            r = ingest(a.project, f, title=a.title or "", doc_no=a.doc_no or "", rev=a.rev or "", doc_date=a.date or "",
                       used_for=a.used_for or "", copy=not a.no_copy)
            if r["error"]:
                print(f"indexed {r['input']} but NOT extracted: {r['error']}")
            else:
                print(f"ingested {r['input']} -> {r['extracted']}")
        print(f"index: {Path(a.project) / 'docs' / 'INDEX.md'}")
        return
    if a.op == "export":
        try:
            out = project_export(a.project, a.to, a.output, a.files or None, pdf_engine=a.pdf_engine or "")
        except RuntimeError as e:
            sys.exit(str(e))
        print(f"wrote {out}")


def cmd_hmi(a):
    from .hmi.spec import load_hmi_spec
    from .hmi.viewdesigner import build_viewdesigner
    proj = load_project(a.project)
    if a.op == "docs":
        from .docs.generate import generate_docs
        print("note: `lf hmi docs` now runs `lf docs build` (HMI_TAGS.md and ALARMS.csv live in docs/generated/)")
        for p in generate_docs(proj):
            print(f"wrote {p}")
        return
    spec = load_hmi_spec(proj)
    if spec is None:
        sys.exit(f"{a.project}/hmi/hmi.json not found (see hmi-view-designer skill)")
    findings = validate(proj, _naming_rules(a.project))
    errs = [f for f in findings if f.level == "error"]
    if errs and not a.force:
        for f in errs:
            print(f, file=sys.stderr)
        sys.exit(f"hmi build aborted: {len(errs)} error(s). Use --force to write anyway.")
    out = Path(a.output) if a.output else Path(a.project) / "build" / "hmi"
    written = build_viewdesigner(proj, spec, out)
    print(f"wrote {len(written)} files under {out / spec.project_name}")
    for w in written:
        print("  ", Path(w).relative_to(out))
    print("View Designer: File > Import Project > select ViewApplication.hmi (controller reference "
          f"'{spec.controller_ref}' must exist in the target project first).")


def cmd_online(a):
    from .online import pycomm3_client as oc
    if a.op == "read":
        print(json.dumps(oc.read_tags(a.path, a.tags), indent=2, default=str))
    elif a.op == "write":
        oc.require_write_permission()
        print(json.dumps(oc.write_tags(a.path, dict(kv.split("=", 1) for kv in a.tags)), indent=2, default=str))
    elif a.op == "info":
        print(json.dumps(oc.controller_info(a.path), indent=2, default=str))
    elif a.op == "tags":
        print(json.dumps(oc.list_tags(a.path, a.program), indent=2, default=str))


def cmd_sdk(a):
    from .online import ld_sdk
    ld_sdk.cli(a)


def main(argv=None):
    ap = argparse.ArgumentParser(prog="lf", description="LogixForge - agentic Studio 5000 toolkit")
    ap.add_argument("--version", action="version", version=f"lf {__version__}")
    sub = ap.add_subparsers(dest="cmd", required=True)

    s = sub.add_parser("init", help="create a new project directory")
    s.add_argument("dir"); s.add_argument("--name", required=True); s.add_argument("--processor", default="1756-L83E")
    s.add_argument("--rev", type=int, default=33); s.add_argument("--force", action="store_true")
    s.add_argument("--profile", help="site profile to apply (profiles/<name>: naming.json + templates)")
    s.add_argument("--git", action="store_true", help="also `git init` the project (one repository per PLC project)")
    s.set_defaults(fn=cmd_init)

    s = sub.add_parser("validate", help="validate a project dir or L5X")
    s.add_argument("path"); s.add_argument("--json", action="store_true"); s.add_argument("--strict", action="store_true")
    s.set_defaults(fn=cmd_validate)

    s = sub.add_parser("build", help="build full L5X from project dir")
    s.add_argument("project"); s.add_argument("-o", "--output"); s.add_argument("--force", action="store_true")
    s.add_argument("--partials", action="store_true", help="also write per-item partial import files"); s.set_defaults(fn=cmd_build)

    s = sub.add_parser("partial", help="write a partial-import L5X for one item")
    s.add_argument("project"); s.add_argument("--kind", required=True,
                                              choices=["Routine", "Program", "Tag", "DataType", "AddOnInstructionDefinition"])
    s.add_argument("--name", required=True); s.add_argument("--program"); s.add_argument("-o", "--output"); s.set_defaults(fn=cmd_partial)

    s = sub.add_parser("inspect", help="summarise a project dir or L5X")
    s.add_argument("path"); s.add_argument("--json", action="store_true"); s.add_argument("--routine", help="PROGRAM/ROUTINE to print")
    s.set_defaults(fn=cmd_inspect)

    s = sub.add_parser("decompile", help="L5X -> editable project dir")
    s.add_argument("l5x"); s.add_argument("-o", "--output", required=True); s.set_defaults(fn=cmd_decompile)

    s = sub.add_parser("diff", help="diff two projects/L5X files (routines, tags, UDTs)")
    s.add_argument("a"); s.add_argument("b"); s.set_defaults(fn=cmd_diff)

    s = sub.add_parser("rung", help="check a single rung's neutral text")
    s.add_argument("op", choices=["check"]); s.add_argument("text"); s.set_defaults(fn=cmd_rung)

    s = sub.add_parser("hmi", help="HMI generation (Studio 5000 View Designer import folder, HMI docs)")
    s.add_argument("op", choices=["build", "docs"]); s.add_argument("project"); s.add_argument("-o", "--output")
    s.add_argument("--force", action="store_true"); s.set_defaults(fn=cmd_hmi)

    s = sub.add_parser("docs", help="project documentation: ingest given documents, generate docs from the spec, export via pandoc")
    s.add_argument("op", choices=["build", "ingest", "export"]); s.add_argument("project")
    s.add_argument("files", nargs="*", help="ingest: documents to add; export: docs/-relative Markdown files to include")
    s.add_argument("-o", "--output"); s.add_argument("--title"); s.add_argument("--doc-no", dest="doc_no"); s.add_argument("--rev")
    s.add_argument("--date"); s.add_argument("--used-for", dest="used_for", help="what the document feeds (naming, interlocks, I/O list ...)")
    s.add_argument("--no-copy", action="store_true", help="ingest: index the file where it is instead of copying to docs/input/")
    s.add_argument("--to", default="docx", choices=["pdf", "docx", "html"]); s.add_argument("--pdf-engine", dest="pdf_engine")
    s.set_defaults(fn=cmd_docs)

    s = sub.add_parser("online", help="live controller access via pycomm3 (EtherNet/IP)")
    s.add_argument("op", choices=["info", "tags", "read", "write"])
    s.add_argument("--path", required=True, help="CIP path e.g. 192.168.1.10/0 or 192.168.1.10/bp/2")
    s.add_argument("--program"); s.add_argument("tags", nargs="*", help="tag names, or Tag=Value for write")
    s.set_defaults(fn=cmd_online)

    s = sub.add_parser("sdk", help="Logix Designer SDK operations (Windows + Studio 5000 v34+)")
    s.add_argument("op", choices=["open", "import", "import-rungs", "build", "download", "upload-export", "online", "read", "write", "mode"])
    s.add_argument("--acd", help=".ACD project path"); s.add_argument("--l5x"); s.add_argument("--path", help="comm path")
    s.add_argument("--target", help="import target for partial import e.g. Controller/Programs/MainProgram")
    s.add_argument("--collision", default="Overwrite", choices=["Overwrite", "Discard", "UseExisting"])
    s.add_argument("--program"); s.add_argument("--routine"); s.add_argument("--tag"); s.add_argument("--value")
    s.add_argument("--type", dest="dtype", default="DINT"); s.add_argument("--mode", choices=["Program", "Run", "Test"])
    s.add_argument("-o", "--output"); s.set_defaults(fn=cmd_sdk)

    a = ap.parse_args(argv)
    try:
        a.fn(a)
    except SpecError as e:
        sys.exit(f"spec error: {e}")


if __name__ == "__main__":
    main()
